-- DISTINCT를 사용하는 이유 : 총 판매 수가 아닌 회원수를 구하기 때문에 중복 회원을 제거해야한다.
SELECT YEAR(B.SALES_DATE) YEAR, MONTH(B.SALES_DATE) MONTH, A.GENDER, COUNT(DISTINCT A.USER_ID) USERS
FROM USER_INFO A
JOIN ONLINE_SALE B
ON A.USER_ID = B.USER_ID
WHERE A.GENDER IS NOT NULL
GROUP BY YEAR(B.SALES_DATE), MONTH(B.SALES_DATE), A.GENDER
ORDER BY YEAR, MONTH, GENDER