-- 코드를 입력하세요
SELECT A.CAR_ID, A.CAR_TYPE, FLOOR(DAILY_FEE * (1-DISCOUNT_RATE/100) * 30) FEE
FROM CAR_RENTAL_COMPANY_CAR A
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN B
USING (CAR_TYPE)
WHERE A.CAR_TYPE IN ('세단', 'SUV')
AND B.DURATION_TYPE LIKE '%30일%'
AND A.CAR_ID NOT IN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE END_DATE >= '2022-11-01' AND START_DATE <= '2022-11-30'
)
HAVING FEE BETWEEN 500000 AND 1999999
ORDER BY FEE DESC, A.CAR_TYPE, A.CAR_ID DESC