-- 인라인뷰
/* SELECT A.YEAR, A.MONTH, A.CNT PUCHASED_USERS, ROUND(A.CNT/B.TOTAL,1) PUCHASED_RATIO
FROM (
    SELECT YEAR(A.SALES_DATE) YEAR
          , MONTH(A.SALES_DATE) MONTH
          , COUNT(DISTINCT A.USER_ID) CNT
     FROM ONLINE_SALE A
     LEFT JOIN USER_INFO B
     ON A.USER_ID = B.USER_ID
     WHERE YEAR(B.JOINED) = '2021'
     GROUP BY YEAR, MONTH
) A,(
    SELECT COUNT(1) TOTAL
     FROM USER_INFO
     WHERE DATE_FORMAT(JOINED, '%Y') = '2021'
) B
ORDER BY YEAR, MONTH */

-- 변수사용
SET @TOTAL := (
    SELECT COUNT(1)
    FROM USER_INFO
    WHERE YEAR(JOINED) = '2021'
);

SELECT YEAR(A.SALES_DATE) YEAR
     , MONTH(A.SALES_DATE) MONTH
     , COUNT(DISTINCT A.USER_ID) PUCHASED_USERS
     , ROUND(COUNT(DISTINCT A.USER_ID)/@TOTAL,1) PUCHASED_RATIO
FROM ONLINE_SALE A
LEFT JOIN USER_INFO B
ON A.USER_ID = B.USER_ID
WHERE YEAR(B.JOINED) = '2021'
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH