-- 코드를 입력하세요
SELECT MONTH(A.START_DATE) MONTH, B.CAR_ID, COUNT(*) RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY A
RIGHT JOIN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE DATE_FORMAT(START_DATE, '%Y-%m') BETWEEN '2022-08' AND '2022-10'
    GROUP BY CAR_ID
    HAVING COUNT(*) > 4
) B
ON A.CAR_ID = B.CAR_ID
WHERE DATE_FORMAT(A.START_DATE, '%Y-%m') BETWEEN '2022-08' AND '2022-10'
GROUP BY MONTH(A.START_DATE), B.CAR_ID
-- HAVING COUNT(*) > 0
ORDER BY MONTH, B.CAR_ID DESC