-- 코드를 입력하세요
WITH RECURSIVE CTE AS -- RECURSIVE : 재귀 여부
(
    SELECT 0 AS N -- 초기값 설정
    UNION ALL
    SELECT N+1 FROM CTE
    WHERE N < 23 -- 재귀 정지 조건
)

SELECT A.N HOUR, COUNT(B.ANIMAL_ID) COUNT
FROM CTE A
LEFT JOIN ANIMAL_OUTS B
ON A.N = HOUR(B.DATETIME)
GROUP BY A.N
ORDER BY HOUR