SELECT A.FLAVOR
FROM FIRST_HALF A
LEFT JOIN (
    SELECT FLAVOR, SUM(TOTAL_ORDER) JULY_SUM
    FROM JULY 
    GROUP BY FLAVOR
) B
ON A.FLAVOR = B.FLAVOR
GROUP BY A.FLAVOR
ORDER BY SUM(TOTAL_ORDER) + JULY_SUM DESC
LIMIT 3


-- USING : JOIN하고자하는 필드명이 같은 경우 사용하며 양쪽 테이블의 키를 모두 조회할 필요가 없어 성능 향상
-- 주의사항 : INNER JOIN에서 사용하는것을 권장
--        : 추가적으로 AND 조건을 사용할 수 없다
/* SELECT FLAVOR
FROM FIRST_HALF A
JOIN JULY B
USING (FLAVOR)
GROUP BY FLAVOR
ORDER BY SUM(A.TOTAL_ORDER + B.TOTAL_ORDER) DESC
LIMIT 3 */